### ISSUE TITLE
Using API Token doesn't pull any zones to select

### ISSUE THREAD

**Issue by cmargroff** [workingconcept/cloudflare-craft-plugin#15]
In Cloudflare permissions are selected as:
Zone, Zone, Read
Zone, Cache Purge, Edit

and Zone Resources as:
Include, Specific zone, [domain]

The settings panel properly verifies the API Token but does not show any zones in the list to select from.

I've also attempted to configure with config/cloudflare.php by setting "apiToken" with the token and "zone" with the Zone ID. I shows the token in the panel but no selected Zone.

I see you have this closed in #14 but it doesn't seem to work on my end.

**Comment by mattstein** [comment]
Thanks for the issue, @cmargroff! I'm using this on a few projects where the _Zone Resources_ setting is `Include` → `All zones from an account` → `[relevant account]` so it's possible to get a listing of zones. Without that permission I believe the plugin would need some alternate UI or at least for the hardcoded config to work as you described.

Are you able to test with that change in permissions and confirm that's the issue?

**Comment by cmargroff** [comment]
We have an enterprise account for Cloudflare and that would give access to all of our clients zones which I can't do.

**Comment by mattstein** [comment]
Okay, well I'll look into hardcoding that setting as soon as I can. Thanks again for pointing this out!

**Comment by mattstein** [comment]
I’ve finally got an update on this, @cmargroff! 

I just added a [handful of improvements](https://github.com/workingconcept/cloudflare-craft-plugin/blob/develop/CHANGELOG.md) to the `develop` branch, including the ability to hard-code the zone ID (or an environment variable for it) in a static config file. There are some new examples in the readme, and if you want to try this you can require `dev-develop as 0.4.1` before it’s released.

I tested with a more limited token and it works as expected—let me know if you try it and run into any issues!

**Comment by mattstein** [comment]
Fixed in [0.4.1](https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/0.4.1).

**Comment by chasegiunta** [comment]
@mattstein I'm still seeing this unfortunately on 0.4.1 . Same zone token configuration as @cmargroff described `Include` → `Specific zone` → `[domain]`

**Comment by mattstein** [comment]
Thanks for mentioning it, @chasegiunta. And just for science, you’re definitely setting the zone ID in `config/cloudflare.php`?

```php
<?php

return [
    'zone' => '$THE_GIUNTA_ZONE',
];
```

**Comment by chasegiunta** [comment]
@mattstein I am now (sorry, just edited my prior comment to show)!

**Comment by mattstein** [comment]
I think the current implementation makes sense when it’s not possible to list zones for selection—but I’m open to ideas and criticism @chasegiunta!

**Comment by chasegiunta** [comment]
@mattstein Gotcha. Yeah it's rather confusing because the user is unable to save the settings via control panel due to the Zone selection being required.

I think the best UI implementation will be to direct the user to configure the zone setting (and all others) through the config file if the `fetch-zones` request returns `[]` after the `verify-connection` call succeeds. Otherwise, others may land here as I did.

**Comment by mattstein** [comment]
Good call @chasegiunta, thanks. I’ll make a new issue and put my best person on it.
